TEAM_COLORS = {
      'ANA': '#D9614B',
      'ARI': '#945057',
      'BOS': '#E6C760',
      'BUF': '#3A4F73',
      'CGY': '#CF5D65',
      'CAR': '#3D3D3D',
      'CHI': '#D05160',
      'COL': '#9A5161',
      'CBJ': '#3A4B6F',
      'DAL': '#3D7A6C',
      'DET': '#D54E54',
      'EDM': '#E76F2B',
      'FLA': '#C59F40',
      'LAK': '#B5BDC0',
      'MTL': '#B55560',
      'MIN': '#3D735E',
      'NSH': '#E6C560',
      'NYR': '#4378B0',
      'NYI': '#3D68A3',
      'NJD': '#CF5D65',
      'OTT': '#D2546A',
      'PHI': '#E08363',
      'PIT': '#E6BD50',
      'SJS': '#3D8896',
      'STL': '#3D7ABD',
      'TBL': '#3D5C8C',
      'TOR': '#3D5B88',
      'VAN': '#3A567E',
      'WSH': '#C14E5C',
      'WPG': '#3A4F73',
      'VGK': '#9A8968',
      'SEA': '#A1DBDB',
      'UTA': '#8AB9E8',
  }

TEAM_NAMES = {
    'ANA': 'Anaheim Ducks',
    'ARI': 'Arizona Coyotes',
    'BOS': 'Boston Bruins',
    'BUF': 'Buffalo Sabres',
    'CGY': 'Calgary Flames',
    'CAR': 'Carolina Hurricanes',
    'CHI': 'Chicago Blackhawks',
    'COL': 'Colorado Avalanche',
    'CBJ': 'Columbus Blue Jackets',
    'DAL': 'Dallas Stars',
    'DET': 'Detroit Red Wings',
    'EDM': 'Edmonton Oilers',
    'FLA': 'Florida Panthers',
    'LAK': 'Los Angeles Kings',
    'MTL': 'Montreal Canadiens',
    'MIN': 'Minnesota Wild',
    'NSH': 'Nashville Predators',
    'NYR': 'New York Rangers',
    'NYI': 'New York Islanders',
    'NJD': 'New Jersey Devils',
    'OTT': 'Ottawa Senators',
    'PHI': 'Philadelphia Flyers',
    'PIT': 'Pittsburgh Penguins',
    'SEA': 'Seattle Kraken',
    'SJS': 'San Jose Sharks',
    'STL': 'St. Louis Blues',
    'TBL': 'Tampa Bay Lightning',
    'TOR': 'Toronto Maple Leafs',
    'VAN': 'Vancouver Canucks',
    'WSH': 'Washington Capitals',
    'WPG': 'Winnipeg Jets',
    'VGK': 'Vegas Golden Knights',
    'UTA': 'Utah Hockey Club',
}